FROM quay.io/centos/centos:stream9

# hadolint ignore=DL3041
RUN dnf install -y findutils rpm-build rpm-sign dos2unix && dnf clean all

# hadolint ignore=SC2039
RUN mkdir -p /rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}

COPY ./docker-build/rpmbuild.sh /

RUN chmod +rx /rpmbuild.sh

ENTRYPOINT ["/rpmbuild.sh"]
