FROM registry.access.redhat.com/ubi8/ubi:8.10-901.1716497712

# hadolint ignore=DL3041
RUN dnf install -y findutils rpm-build rpm-sign dos2unix && dnf clean all

# hadolint ignore=SC2039,SC3009
RUN mkdir -p /rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}

COPY ./docker-build/rpmbuild.sh /

RUN chmod +rx /rpmbuild.sh

ENTRYPOINT ["/rpmbuild.sh"]
