FROM oraclelinux:7.9

# hadolint ignore=DL3033
RUN yum install -y findutils rpm-build rpm-sign dos2unix tar && yum clean all

# hadolint ignore=SC2039,SC3009
RUN mkdir -p /rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}

COPY ./docker-build/rpmbuild.sh /

RUN chmod +rx /rpmbuild.sh

ENTRYPOINT ["/rpmbuild.sh"]
