name: RPM Build

on:
  workflow_call:
    inputs:
      rpm_name:
        required: true
        type: string
        description: The name of the RPM.
      rhel-version:
        required: false
        type: number
        default: 8
        description: Version of RHEL.
      rpm_push_command:
        required: false
        type: string
        description: Command which needs to be executed to push the rpm to something.
    # secrets:
    #   sign_key:
    #     required: true
    #     description: Key to sign the RPM.

jobs:
  build_rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Set given package name
        if: ${{ inputs.rpm_name }}
        run: echo "rpm_name=${{ inputs.rpm_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push RHEL 7
        if: ${{ inputs.rhel_version == 7 }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-build/Dockerfile.centos-7
          load: true
          tags: build-rpm-rhel7
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push RHEL 8
        if: ${{ inputs.rhel_version == 8 }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-build/Dockerfile.centos-8
          load: true
          tags: build-rpm-rhel8
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build RPM
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
          RPM_NAME: ${{ env.rpm_name }}
          RPM_SIGN_KEY: ${{ secrets.BLA }}
          RPM_SIGN_KEY_PASSPHRASE: ${{ secrets.FOO }}
        run: |
          docker run --rm \
                     -v "$WORKSPACE:/workspace" \
                     -w /workspace/pogo-build/src/rpmbuild \
                     build-rpm-rhel${{ inputs.rhel_version }} ./scope-rpmbuild.sh -w /workspace -m $MAJOR -n $MINOR -b $BUILD_NUMBER

      - uses: actions/upload-artifact@v2
        with:
          name: RPMs
          path: /home/runner/rpmbuild/RPMS/

      - uses: actions/upload-artifact@v2
        with:
          name: SRPMS
          path: /home/runner/rpmbuild/SRPMS/

      - name: Push RPM
        if: ${{ inputs.rpm_push_command }}
        run: ${{ inputs.rpm_push_command }}
